runner:
  n_epochs: -1
  total_steps: 200000
  gradient_clipping: 5.0
  gradient_accumulate_steps: 1
  num_workers: 24
  log_step: 50
  save_step: 5000
  max_keep: 10

  fp16: true
  surgery: true

optimizer:
  name: AdamW_with_schedule
  lr: 2.e-4
  warmup_proportion: 0.07
  betas: [0.9, 0.98]
  eps: 1.e-6
  weight_decay: 1.e-6

pretrain_expert:
  datarc:
    data_stats:
      wav_mean: -9.3908800007092e-13
      wav_std: 0.16258983314037323
      fbank_mean: -4.615277596840262
      fbank_std: 3.360682519086203
    train_batch_size: 24
    num_workers: 24
    max_timestep: 0
    libri_root: /
    file_path: /mnt/data/ycevan/johnwei/s3prl/s3prl/data/len_for_bucket
    sets: ['humert']
